# Generated by Django 5.2.7 on 2026-06-04 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Default/fixed charge amount for this category', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Charge Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='feerecord',
            name='misc_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of miscellaneous charges for this period.', max_digits=10),
        ),
        migrations.CreateModel(
            name='MiscCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('charge_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='fees.chargecategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='misc_charges', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
    ]
