# Generated by Django 5.2.7 on 2026-09-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_migrate_receipt_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='paid_current_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='paid_misc_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='paid_previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
