# Generated by Django 5.2.7 on 2026-09-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_feerecord_paid_current_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='late_paid_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
