# Generated by Django 5.2.7 on 2026-09-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_restore_student_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='advance_applied',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Part of amount_paid that came from the student's advance credit.", max_digits=10),
        ),
    ]
