"""
Django settings for the_creative_school project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from decouple import config
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool, default=False)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])

# Render injects the service's own public hostname into every deploy. Trusting
# it here means a deploy cannot fail on a forgotten ALLOWED_HOSTS entry, and the
# value stays correct if the service is ever renamed. Anything set explicitly in
# ALLOWED_HOSTS is kept as well.
RENDER_EXTERNAL_HOSTNAME = config('RENDER_EXTERNAL_HOSTNAME', default='')
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    # myapps
    'students',
    'accounts',
    'fees',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files (the admin's CSS/JS) straight from the web
    # process — Render has no separate static host. Must sit directly after
    # SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'the_creative_school.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'the_creative_school.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE':   'django.db.backends.postgresql',
        'NAME':     config('DB_NAME'),       
        'USER':     config('DB_USER'),       
        'PASSWORD': config('DB_PASSWORD'),
        'HOST':     config('DB_HOST'),       
        'PORT':     config('DB_PORT', default='5432'),
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# The school is in Pakistan. Left at UTC, every timestamp read five hours
# behind the clock on the wall, and worse, a payment taken after 5pm local was
# stamped with the previous day's date — timezone.now().date() was resolving in
# UTC. Timestamps are still stored in UTC (USE_TZ below); this is the zone they
# are recorded and displayed in.
TIME_ZONE = config('TIME_ZONE', default='Asia/Karachi')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
# collectstatic writes here at build time; WhiteNoise serves from it at runtime.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

MEDIA_URL = '/media/'
# NOTE: on Render's free tier this directory is wiped on every deploy. Nothing
# in the app writes uploads today; if that changes, move media to object storage.
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ── Response hardening ────────────────────────────────
# The API is consumed by our own frontend; nothing should frame it, sniff a
# response into a different content type, or leak a full URL as a referrer.
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

# Production hardening. Gated on DEBUG so local development over plain HTTP is
# untouched — with these on, a dev server would redirect to https and the login
# cookie would never be sent.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# ── CORS / CSRF ───────────────────────────────────────
# In production the browser only ever talks to the Vercel domain: Next rewrites
# /api and /admin to this backend server-side, so the requests reaching Django
# are not cross-origin and CORS is not what makes them work. These stay
# env-driven anyway, for anything that does call the API directly.
_csv = lambda v: [s.strip() for s in v.split(',') if s.strip()]

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://localhost:5173',
    cast=_csv,
)

# Needed to log into /admin/ through the deployed domain — Django checks the
# Origin of the POST against this list.
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=_csv)
if RENDER_EXTERNAL_HOSTNAME:
    _render_origin = f'https://{RENDER_EXTERNAL_HOSTNAME}'
    if _render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_render_origin)

# ── Request size limits ───────────────────────────────
# A JSON body big enough to exhaust memory is the cheapest denial-of-service
# there is. 2 MB is far more than any payload this API accepts (the largest is
# a bulk-generate for the whole school, a few hundred bytes).
DATA_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024

# ── Cache (backs the throttles) ───────────────────────
# Throttle counters live in the cache. The default per-process memory cache
# would give each Gunicorn worker its own counter, so a brute-force attempt
# would get N times the allowance and the count would reset on every deploy.
# The database is already there and is shared by every worker.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
    }
}

# ── DRF ───────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAdminUser',
    ),
    # DRF ships the browsable HTML API on by default. It is genuinely useful
    # while developing and is a liability in production: it publishes the shape
    # of every endpoint and renders write forms for them. Keep it locally, serve
    # plain JSON once DEBUG is off.
    'DEFAULT_RENDERER_CLASSES': (
        ('rest_framework.renderers.JSONRenderer',
         'rest_framework.renderers.BrowsableAPIRenderer')
        if DEBUG else
        ('rest_framework.renderers.JSONRenderer',)
    ),
    # Nothing internal ever reaches the client; see exceptions.py.
    'EXCEPTION_HANDLER': 'the_creative_school.exceptions.api_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        # Unauthenticated traffic has almost nothing legitimate to do here.
        'anon': '30/hour',
        # A busy clerk generating records and receipts stays well under this.
        'user': '1200/hour',
        # Login, all keyed on the username being tried (see accounts/throttling.py).
        # Sized for a person who mistypes, not for a machine: five tries in a
        # minute covers a bad keyboard day, thirty in an hour does not survive a
        # guessing loop. A correct password clears both counters.
        'login_burst':     '5/min',
        'login_sustained': '30/hour',
        # Per source address, looser because a whole school shares one
        # connection. Catches one host spraying many different usernames.
        'login_ip':        '60/hour',
        # Refresh happens automatically about once an hour per signed-in user;
        # this is abuse limiting, not secret protection.
        'refresh': '200/hour',
        # Endpoints that build a PDF or workbook cost real CPU per call.
        'reports': '120/hour',
    },
}

# ── JWT ───────────────────────────────────────────────
SIMPLE_JWT = {
    # Two different clocks:
    #
    # ACCESS_TOKEN_LIFETIME is how long a single token is usable before the
    # frontend silently swaps it for a new one. Short, because a token copied
    # off a shared office machine stops working quickly. The user never notices
    # this expiring — api/client.js refreshes on the first 401.
    'ACCESS_TOKEN_LIFETIME':  timedelta(hours=1),
    #
    # REFRESH_TOKEN_LIFETIME is the real answer to "how long do I stay signed
    # in": once this lapses the password must be typed again. Because tokens
    # rotate below, the clock restarts on every refresh — so it behaves as
    # twelve hours of *inactivity*, not twelve hours flat. Someone using the
    # app all day is never interrupted; a machine left overnight asks for the
    # password in the morning.
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=12),
    #
    # Each refresh issues a fresh refresh token, which is what makes the window
    # sliding rather than absolute. api/client.js stores the new one.
    'ROTATE_REFRESH_TOKENS':  True,
    'AUTH_HEADER_TYPES':      ('Bearer',),
}


# ── Logging ───────────────────────────────────────────
# Unhandled faults are logged with a reference the user is shown, so a support
# report can be tied to a traceback. Render captures stdout, so a console
# handler is all that is needed there.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'the_creative_school': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django logs every 4xx/5xx it raises here; without this they are
        # swallowed in production.
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
